version: '3.3'

services:
  wordpress:
    image: wordpress:latest
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    ports:
      - 8080:80
    volumes:
      - ./wordpress:/var/www/html
    depends_on:
      - db
    networks:
      - wpnet

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wpnet

  webserver:
    image: nginx:latest
    ports:
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certs:/etc/nginx/certs
      - ./wordpress:/var/www/html
    depends_on:
      - wordpress
    networks:
      - wpnet
  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: "no"
    command: certonly --webroot --webroot-path=/var/www/html --email $EMAIL --agree-tos -d $DOMAIN
    volumes:
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - nginx
      networks:
       wpnet:
networks:
  wpnet:

volumes:
  db_data:
